### ISSUE TITLE
Not possible to create an RRuleSet with timezone "local"

### ISSUE THREAD

**Issue by tomquist** [lsndr/rrule-rust#157]
With the new API it's not possible to create an RRuleSet with the timezone set to "local", e.g. this fails:
```
new RRuleSet(DateTime.create(2024, 1, 1, 0, 0, 0, false), "local");
// => Error: 'local' is not a valid timezone
```
The reason is that timezones always get parsed with `chrono_tz` and then passed into `rrule::Tz::Tz`. Should `local` and `utc` be treated as a special string to instruct the `RRuleSet` constructor to use `rrule::Tz::LOCAL` or `rrule::Tz::UTC` respectively?

**Comment by lsndr** [comment]
It's also not possible to create `RRuleSet` with `local` timezone in 1.2.0. Probably it was possible in some of 2.0.0-next.* pre-releases.

What is the use-case for this and how it should behave?

As I see it:

There is no such timezone as `local`. DateTime can be `local` or `utc`: when it's `local` it is calculated in context of some time zone, `utc` is timezone independent.

Probably we can convert `local` to current timezone, when `local` is passed, but again - there is no such timezone as local. The same can be achieved using:

```
new RRuleSet(DateTime.create(2024, 1, 1, 0, 0, 0, false), Intl.DateTimeFormat().resolvedOptions().timeZone);
```

**Comment by tomquist** [comment]
The problem is, that UNTIL and DTSTART must be synchronized and there are several validations that enforce this (see [here](https://github.com/fmeringdal/rust-rrule/blob/ec5a9b9d74151e8523d60e522a5432ea126d0f9d/rrule/src/validator/validate_rrule.rs#L50)):

 However, we only have control over the DTSTART timezone and the UNTIL value gets parsed from the RRULE. E.g. the DTSTART must be in local time zone in order to parse this RRULE:
```
RRULE:FREQ=WEEKLY;WKST=MO;UNTIL=20220513;BYDAY=FR,TH,TU,WE
```
This gets validated by this validation: https://github.com/fmeringdal/rust-rrule/blob/ec5a9b9d74151e8523d60e522a5432ea126d0f9d/rrule/src/validator/validate_rrule.rs#L68

So without being able to instantiate an `RRuleSet` in `local` timezone, it's not easily possible to parse such an RRULE.

**Comment by lsndr** [comment]
Yeah, in rust's crate `UNTIL` and `DTSTART` must be in sync. But in 2.0.0 this problem is solved by timezone conversion https://github.com/lsndr/rrule-rust/blob/cda2986209a187af07ca12e2ba8be66f730da182/lib/js/rrule.rs#L315-L319

So in the provided example `UNTIL=20220513` is treated as `local` datetime which is not bound to any timezone. When you add to to `RRuleSet` it's calculated against `RRuleSet`'s `tzid`.

Are you talking about `set.setFromString` method? I just noticed it raises for the string you provided. It works fine in this situation:

```typescript
const rrule = RRule.parse('RRULE:FREQ=WEEKLY;WKST=MO;UNTIL=20220513;BYDAY=FR,TH,TU,WE');
const set = new RRuleSet().addRrule(rrule);

console.log(set.toString());
```

but fails here:

```typescript
const set = new RRuleSet().setFromString('RRULE:FREQ=WEEKLY;WKST=MO;UNTIL=20220513;BYDAY=FR,TH,TU,WE');

console.log(set.toString());
```

So this is definitely a bug and should work the same as the first example.

**Comment by tomquist** [comment]
Ah, I missed that this validation exists. Yes, I'm using `setFromString()` because we're actually reading from an array that contains a mix of RRULE, RDATE or EXDATE.

**Comment by tomquist** [comment]
I couldn't find an easy workaround that wouldn't require me to parse EXDATE or RDATE by myself. I tried calling `setFromString()` without the RRULE, but this errors out if the only other rules are `EXDATE`s. Another option would be to construct the `DTSTART` string manually, depending on which timezone `UNTIL` uses, and then pass it to `RRuleSet.parse()`, but that defeats the purpose of `setFromString()`.

**Comment by lsndr** [comment]
Ok, I think I'll implement own parser of rrule strings in rust, and will use it inside this method and I think all other string methods. Since original is a bit buggy: for example it does not properly output UNTIL date https://github.com/lsndr/rrule-rust/blob/f76099cb6c0e576df01ed677d7d59bafee21d00a/tests/yearly.spec.ts#L184-L189

**Comment by lsndr** [comment]
@tomquist i've just merged a fix for this issue. It changed behavior in some cases and fixed some known bugs related to serialization. See modified tests in #164

It's not ideal in terms of rust code quality. I'll work on this additionally as a part of #165. But in terms of use cases seems to be working well
