### ISSUE TITLE
Return JS Date instances instead of UNIX timestamps

### ISSUE THREAD

**Issue by tomquist** [lsndr/rrule-rust#37]
I would like to discuss whether it would be better for the API to return JS date instances instead of UNIX timestamps. While this may make it slightly slower, it would also make it more convenient to use. In reality, it shouldn't have a significant impact since, on the JS side, timestamps would likely be converted into JS dates regardless. What was the main reason for choosing UNIX timestamps in the first place?

**Comment by lsndr** [comment]
This is a good question.

I choose timestamp instead of Date object because I don't like the way Date object is used in NPM's rrule package. It's obviously doesn't work well with rrule spec, since it doesn't support time zones.

I was thinking about adding [luxon](https://www.npmjs.com/package/luxon), or creating own simple date object with some useful conversion methods like:

```typescript
class RRuleDate {
  day: number;
  month: number;
  year: number;
  hour: number;
  minute: number;
  second: number:

 toDate(): Date {}

 toUTCDate(): Date {}
}
```
